<?php

/**
 * Colombia places
 *
 * @author   Saul Morales Pacheco <moralespachecopablo@gmail.com>
 * @version  1.1.33
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */
global $places;

$places['CO'] = array(
	'AMZ' => array(
        "El Encanto",
        "La Chorrera",
        "La Pedrera",
        "La Victoria",
        "Leticia",
        "Miriti - Paraná",
        "Puerto Alegría",
        "Puerto Arica",
        "Puerto Nariño",
        "Puerto Santander",
        "Tarapacá",
    ),
	'ANT' => array(
        "Abejorral",
        "Abriaquí",
        "Alejandría",
        "Amagá",
        "Amalfi",
        "Andes",
        "Angelópolis",
        "Angostura",
        "Anorí",
        "Anza",
        "Apartadó",
        "Arboletes",
        "Argelia",
        "Armenia",
        "Barbosa",
        "Bello",
        "Belmira",
        "Betania",
        "Betulia",
        "Briceño",
        "Buriticá",
        "Cáceres",
        "Caicedo",
        "Caldas",
        "Campamento",
        "Cañasgordas",
        "Caracolí",
        "Caramanta",
        "Carepa",
        "Carolina",
        "Caucasia",
        "Chigorodó",
        "Cisneros",
        "Ciudad Bolívar",
        "Cocorná",
        "Concepción",
        "Concordia",
        "Copacabana",
        "Dabeiba",
        "Don Matías",
        "Ebéjico",
        "El Bagre",
        "El Carmen De Viboral",
        "El Santuario",
        "Entrerrios",
        "Envigado",
        "Fredonia",
        "Frontino",
        "Giraldo",
        "Girardota" =>'5308',
        "Gómez Plata",
        "Granada",
        "Guadalupe",
        "Guarne",
        "Guatape",
        "Heliconia",
        "Hispania",
        "Itagui",
        "Ituango",
        "Jardín",
        "Jericó",
        "La Ceja",
        "La Estrella",
        "La Pintada",
        "La Unión",
        "Liborina",
        "Maceo",
        "Marinilla",
        "Medellín",
        "Montebello",
        "Murindó",
        "Mutatá",
        "Nariño",
        "Nechí",
        "Necoclí",
        "Olaya",
        "Peñol",
        "Peque",
        "Pueblorrico",
        "Puerto Berrío",
        "Puerto Nare",
        "Puerto Triunfo",
        "Remedios",
        "Retiro",
        "Rionegro",
        "Sabanalarga",
        "Sabaneta",
        "Salgar",
        "San Andrés",
        "San Carlos",
        "San Francisco",
        "San Jerónimo",
        "San José De La Montaña",
        "San Juan De Urabá",
        "San Luis",
        "San Pedro",
        "San Pedro De Uraba",
        "San Rafael",
        "San Roque",
        "San Vicente",
        "Santa Bárbara",
        "Santa Rosa De Osos",
        "Santafé De Antioquia",
        "Santo Domingo",
        "Segovia",
        "Sonson",
        "Sopetrán",
        "Támesis",
        "Tarazá",
        "Tarso",
        "Titiribí",
        "Toledo",
        "Turbo",
        "Uramita",
        "Urrao",
        "Valdivia",
        "Valparaíso",
        "Vegachí",
        "Venecia",
        "Vigía Del Fuerte",
        "Yalí",
        "Yarumal",
        "Yolombó",
        "Yondó",
        "Zaragoza",

    ),
	'ARU' => array(
        "Arauca",
        "Arauquita",
        "Cravo Norte",
        "Fortul",
        "Puerto Rondón",
        "Saravena",
        "Tame",
    ),
	'ATL' => array(
        "Baranoa",
        "Barranquilla",
        "Campo De La Cruz",
        "Candelaria",
        "Galapa",
        "Juan De Acosta",
        "Luruaco",
        "Malambo",
        "Manatí",
        "Palmar De Varela",
        "Piojó",
        "Polonuevo",
        "Ponedera",
        "Puerto Colombia",
        "Repelón",
        "Sabanagrande",
        "Sabanalarga",
        "Santa Lucía",
        "Santo Tomás",
        "Soledad",
        "Suan",
        "Tubará",
        "Usiacurí",
    ),
    'BDC' => array(
        "Bogotá",
    ),
	'BOL' => array(
        "Achí",
        "Altos Del Rosario",
        "Arenal",
        "Arjona",
        "Arroyohondo",
        "Barranco De Loba",
        "Calamar",
        "Cantagallo",
        "Cartagena",
        "Cicuco",
        "Clemencia",
        "Córdoba",
        "El Carmen De Bolívar",
        "El Guamo",
        "El Peñón",
        "Hatillo De Loba",
        "Magangué",
        "Mahates",
        "Margarita",
        "María La Baja",
        "Mompós",
        "Montecristo",
        "Morales",
        "Pinillos",
        "Regidor",
        "Río Viejo",
        "San Cristóbal",
        "San Estanislao",
        "San Fernando",
        "San Jacinto",
        "San Jacinto Del Cauca",
        "San Juan Nepomuceno",
        "San Martín De Loba",
        "San Pablo",
        "Santa Catalina",
        "Santa Rosa",
        "Santa Rosa Del Sur",
        "Simití",
        "Soplaviento",
        "Talaigua Nuevo",
        "Tiquisio",
        "Turbaco",
        "Turbaná",
        "Villanueva",
        "Zambrano",
    ),
	'BOY' => array(
        "Almeida",
        "Aquitania",
        "Arcabuco",
        "Belén",
        "Berbeo",
        "Betéitiva",
        "Boavita",
        "Boyacá",
        "Briceño",
        "Buenavista",
        "Busbanzá",
        "Caldas",
        "Campohermoso",
        "Cerinza",
        "Chinavita",
        "Chiquinquirá",
        "Chíquiza",
        "Chiscas",
        "Chita",
        "Chitaraque",
        "Chivatá",
        "Chivor",
        "Ciénega",
        "Cómbita",
        "Coper",
        "Corrales",
        "Covarachía",
        "Cubará",
        "Cucaita",
        "Cuítiva",
        "Duitama",
        "El Cocuy",
        "El Espino",
        "Firavitoba",
        "Floresta",
        "Gachantivá",
        "Gameza",
        "Garagoa",
        "Guacamayas",
        "Guateque",
        "Guayatá",
        "Güicán",
        "Iza",
        "Jenesano",
        "Jericó",
        "La Capilla",
        "La Uvita",
        "La Victoria",
        "Labranzagrande",
        "Macanal",
        "Maripí",
        "Miraflores",
        "Mongua",
        "Monguí",
        "Moniquirá",
        "Motavita",
        "Muzo",
        "Nobsa",
        "Nuevo Colón",
        "Oicatá",
        "Otanche",
        "Pachavita",
        "Páez",
        "Paipa",
        "Pajarito",
        "Panqueba",
        "Pauna",
        "Paya",
        "Paz De Río",
        "Pesca",
        "Pisba",
        "Puerto Boyacá",
        "Quípama",
        "Ramiriquí",
        "Ráquira",
        "Rondón",
        "Saboyá",
        "Sáchica",
        "Samacá",
        "San Eduardo",
        "San José De Pare",
        "San Luis De Gaceno",
        "San Mateo",
        "San Miguel De Sema",
        "San Pablo De Borbur",
        "Santa María",
        "Santa Rosa De Viterbo",
        "Santa Sofía",
        "Santana",
        "Sativanorte",
        "Sativasur",
        "Siachoque",
        "Soatá",
        "Socha",
        "Socotá",
        "Sogamoso",
        "Somondoco",
        "Sora",
        "Soracá",
        "Sotaquirá",
        "Susacón",
        "Sutamarchán",
        "Sutatenza",
        "Tasco",
        "Tenza",
        "Tibaná",
        "Tibasosa",
        "Tinjacá",
        "Tipacoque",
        "Toca",
        "Togüí",
        "Tópaga",
        "Tota",
        "Tunja",
        "Tununguá",
        "Turmequé",
        "Tuta",
        "Tutazá",
        "Umbita",
        "Ventaquemada",
        "Villa De Leyva",
        "Viracachá",
        "Zetaquira",
    ),
	'CAL' => array(
        "Aguadas",
        "Anserma",
        "Aranzazu",
        "Belalcázar",
        "Chinchiná",
        "Filadelfia",
        "La Dorada",
        "La Merced",
        "Manizales",
        "Manzanares",
        "Marmato",
        "Marquetalia",
        "Marulanda",
        "Neira",
        "Norcasia",
        "Pácora",
        "Palestina",
        "Pensilvania",
        "Riosucio",
        "Risaralda",
        "Salamina",
        "Samaná",
        "San José",
        "Supía",
        "Victoria",
        "Villamaría",
        "Viterbo",
    ),
	'CAQ' => array(
        "Albania",
        "Belén De Los Andaquies",
        "Cartagena Del Chairá",
        "Curillo",
        "El Doncello",
        "El Paujil",
        "Florencia",
        "La Montañita",
        "Milán",
        "Morelia",
        "Puerto Rico",
        "San José Del Fragua",
        "San Vicente Del Caguán",
        "Solano",
        "Solita",
        "Valparaíso",
    ),
	'CAS' => array(
        "Aguazul",
        "Chameza",
        "Hato Corozal",
        "La Salina",
        "Maní",
        "Monterrey",
        "Nunchía",
        "Orocué",
        "Paz De Ariporo",
        "Pore",
        "Recetor",
        "Sabanalarga",
        "Sácama",
        "San Luis De Palenque",
        "Támara",
        "Tauramena",
        "Trinidad",
        "Villanueva",
        "Yopal",
    ),
	'CAU' => array(
        "Almaguer",
        "Argelia",
        "Balboa",
        "Bolívar",
        "Buenos Aires",
        "Cajibío",
        "Caldono",
        "Caloto",
        "Corinto",
        "El Tambo",
        "Florencia",
        "Guapi",
        "Inzá",
        "Jambaló",
        "La Sierra",
        "La Vega",
        "López",
        "Mercaderes",
        "Miranda",
        "Morales",
        "Padilla",
        "Paez",
        "Patía",
        "Piamonte",
        "Piendamó",
        "Popayán",
        "Puerto Tejada",
        "Puracé",
        "Rosas",
        "San Sebastián",
        "Santa Rosa",
        "Santander De Quilichao",
        "Silvia",
        "Sotara",
        "Suárez",
        "Sucre",
        "Timbío",
        "Timbiquí",
        "Toribio",
        "Totoró",
        "Villa Rica",
        "Guachené",
    ),
	'CES' => array(
        "Aguachica",
        "Agustín Codazzi",
        "Astrea",
        "Becerril",
        "Bosconia",
        "Chimichagua",
        "Chiriguaná",
        "Curumaní",
        "El Copey",
        "El Paso",
        "Gamarra",
        "González",
        "La Gloria",
        "La Jagua De Ibirico",
        "La Paz",
        "Manaure",
        "Pailitas",
        "Pelaya",
        "Pueblo Bello",
        "Río De Oro",
        "San Alberto",
        "San Diego",
        "San Martín",
        "Tamalameque",
        "Valledupar",
    ),
	'CHOC'  => array(
        "Acandí",
        "Alto Baudo",
        "Atrato",
        "Bagadó",
        "Bahía Solano",
        "Bajo Baudó",
        "Belén De Bajirá",
        "Bojaya",
        "Carmen Del Darien",
        "Cértegui",
        "Condoto",
        "El Cantón Del San Pablo",
        "El Carmen De Atrato",
        "El Litoral Del San Juan",
        "Istmina",
        "Juradó",
        "Lloró",
        "Medio Atrato",
        "Medio Baudó",
        "Medio San Juan",
        "Nóvita",
        "Nuquí",
        "Quibdó",
        "Río Iro",
        "Río Quito",
        "Riosucio",
        "San José Del Palmar",
        "Sipí",
        "Tadó",
        "Unguía",
        "Unión Panamericana",
    ),
	'COR' => array(
        "Ayapel",
        "Buenavista",
        "Canalete",
        "Cereté",
        "Chimá",
        "Chinú",
        "Ciénaga De Oro",
        "Cotorra",
        "La Apartada",
        "Lorica",
        "Los Córdobas",
        "Momil",
        "Montelíbano",
        "Montería",
        "Moñitos",
        "Planeta Rica",
        "Pueblo Nuevo",
        "Puerto Escondido",
        "Puerto Libertador",
        "Purísima",
        "Sahagún",
        "San Andrés Sotavento",
        "San Antero",
        "San Bernardo Del Viento",
        "San Carlos",
        "San Pelayo",
        "Tierralta",
        "Valencia",
        "San José de Uré",
    ),
	'CUN' => array(
        "Agua De Dios",
        "Albán",
        "Anapoima",
        "Anolaima",
        "Apulo",
        "Arbeláez",
        "Beltrán",
        "Bituima",
        "Bojacá",
        "Cabrera",
        "Cachipay",
        "Cajicá",
        "Caparrapí",
        "Caqueza",
        "Carmen De Carupa",
        "Chaguaní",
        "Chía",
        "Chipaque",
        "Choachí",
        "Chocontá",
        "Cogua",
        "Cota",
        "Cucunubá",
        "El Colegio",
        "El Peñón",
        "El Rosal",
        "Facatativá",
        "Fomeque",
        "Fosca",
        "Funza",
        "Fúquene",
        "Fusagasugá",
        "Gachala",
        "Gachancipá",
        "Gachetá",
        "Gama",
        "Girardot",
        "Granada",
        "Guachetá",
        "Guaduas",
        "Guasca",
        "Guataquí",
        "Guatavita",
        "Guayabal De Siquima",
        "Guayabetal",
        "Gutiérrez",
        "Jerusalén",
        "Junín",
        "La Calera",
        "La Mesa",
        "La Palma",
        "La Peña",
        "La Vega",
        "Lenguazaque",
        "Macheta",
        "Madrid",
        "Manta",
        "Medina",
        "Mosquera",
        "Nariño",
        "Nemocón",
        "Nilo",
        "Nimaima",
        "Nocaima",
        "Pacho",
        "Paime",
        "Pandi",
        "Paratebueno",
        "Pasca",
        "Puerto Salgar",
        "Pulí",
        "Quebradanegra",
        "Quetame",
        "Quipile",
        "Ricaurte",
        "San Antonio Del Tequendama",
        "San Bernardo",
        "San Cayetano",
        "San Francisco",
        "San Juan De Río Seco",
        "Sasaima",
        "Sesquilé",
        "Sibaté",
        "Silvania",
        "Simijaca",
        "Soacha",
        "Sopó",
        "Subachoque",
        "Suesca",
        "Supatá",
        "Susa",
        "Sutatausa",
        "Tabio",
        "Tausa",
        "Tena",
        "Tenjo",
        "Tibacuy",
        "Tibirita",
        "Tocaima",
        "Tocancipá",
        "Topaipí",
        "Ubalá",
        "Ubaque",
        "Une",
        "Útica",
        "Venecia",
        "Vergara",
        "Vianí",
        "Villa De San Diego De Ubate",
        "Villagómez",
        "Villapinzón",
        "Villeta",
        "Viotá",
        "Yacopí",
        "Zipacón",
        "Zipaquirá",
    ),
	'GUA' => array(
        "Barranco Minas",
        "Cacahual",
        "Inírida",
        "La Guadalupe",
        "Mapiripana",
        "Morichal",
        "Pana Pana",
        "Puerto Colombia",
        "San Felipe",
    ),
	'GUV' => array(
        "Calamar",
        "El Retorno",
        "Miraflores",
        "San José del Guaviare",
    ),
	'HUI' => array(
        "Acevedo",
        "Agrado",
        "Aipe",
        "Algeciras",
        "Altamira",
        "Baraya",
        "Campoalegre",
        "Colombia",
        "Elías",
        "Garzon",
        "Gigante",
        "Guadalupe",
        "Hobo",
        "Iquira",
        "Isnos",
        "La Argentina",
        "La Plata",
        "Nataga",
        "Neiva",
        "Oporapa",
        "Paicol",
        "Palermo",
        "Palestina",
        "Pital",
        "Pitalito",
        "Rivera",
        "Saladoblanco",
        "San Agustín",
        "Santa María",
        "Suaza",
        "Tarqui",
        "Tello",
        "Teruel",
        "Tesalia",
        "Timaná",
        "Villavieja",
        "Yaguará",
    ),
	'GUJ' => array(
        "Albania",
        "Barrancas",
        "Dibulla",
        "Distraccion",
        "El Molino",
        "Fonseca",
        "Hatonuevo",
        "La Jagua del Pilar",
        "Maicao",
        "Manaure",
        "Riohacha",
        "San Juan del Cesar",
        "Uribia",
        "Urumita",
        "Villanueva",
    ),
	'MAG' => array(
        "Algarrobo",
        "Aracataca",
        "Ariguaní",
        "Cerro San Antonio",
        "Chibolo",
        "Cienaga",
        "Concordia",
        "El Banco",
        "El Piñon",
        "El Retén",
        "Fundación",
        "Guamal",
        "Nueva Granada",
        "Pedraza",
        "Pijiño del Carmen",
        "Pivijay",
        "Plato",
        "Puebloviejo",
        "Remolino",
        "Sabanas de San Angel",
        "Salamina",
        "San Sebastián de Buenavista",
        "San Zenón",
        "Santa Ana",
        "Santa Bárbara De Pinto",
        "Sitionuevo",
        "Tenerife",
        "Zapayán",
        "Zona Bananera",
    ),
	'MET' => array(
        "Acacias",
        "Barranca De Upía",
        "Cabuyaro",
        "Castilla La Nueva",
        "Cubarral",
        "Cumaral",
        "El Calvario",
        "El Castillo",
        "El Dorado",
        "Fuente De Oro",
        "Granada",
        "Guamal",
        "La Macarena",
        "Lejanías",
        "Mapiripán",
        "Mesetas",
        "Puerto Concordia",
        "Puerto Gaitán",
        "Puerto Lleras",
        "Puerto López",
        "Puerto Rico",
        "Restrepo",
        "San Carlos De Guaroa",
        "San Juan De Arama",
        "San Juanito",
        "San Martín",
        "Uribe",
        "Villavicencio",
        "Vistahermosa",
    ),
	'NAR' => array(
        "Albán",
        "Aldana",
        "Ancuyá",
        "Arboleda",
        "Barbacoas",
        "Belén",
        "Buesaco",
        "Chachagüí",
        "Colón",
        "Consaca",
        "Contadero",
        "Córdoba",
        "Cuaspud",
        "Cumbal",
        "Cumbitara",
        "El Charco",
        "El Peñol",
        "El Rosario",
        "El Tablón De Gómez",
        "El Tambo",
        "Francisco Pizarro",
        "Funes",
        "Guachucal",
        "Guaitarilla",
        "Gualmatan",
        "Iles",
        "Imues",
        "Ipiales",
        "La Cruz",
        "La Florida",
        "La Llanada",
        "La Tola",
        "La Unión",
        "Leiva",
        "Linares",
        "Los Andes",
        "Magüi",
        "Mallama",
        "Mosquera",
        "Nariño",
        "Olaya Herrera",
        "Ospina",
        "Pasto",
        "Policarpa",
        "Potosi",
        "Providencia",
        "Puerres",
        "Pupiales",
        "Ricaurte",
        "Roberto Payán",
        "Samaniego",
        "San Bernardo",
        "San Lorenzo",
        "San Pablo",
        "San Pedro de Cartago",
        "Sandoná",
        "Santa Bárbara",
        "Santacruz",
        "Sapuyes",
        "Taminango",
        "Tangua",
        "Tumaco",
        "Tuquerres",
        "Yacuanquer",
    ),
	'NOR' => array(
        "Abrego",
        "Arboledas",
        "Bochalema",
        "Bucarasica",
        "Cachirá",
        "Cácota",
        "Chinácota",
        "Chitaga",
        "Convención",
        "Cúcuta",
        "Cucutilla",
        "Durania",
        "El Carmen",
        "El Zulia",
        "Gramalote",
        "Hacarí",
        "Herran",
        "La Esperanza",
        "Los Playa",
        "Labateca",
        "Los Patios",
        "Lourdes",
        "Mutiscua",
        "Ocaña",
        "Pamplona",
        "Pamplonita",
        "Puerto santander",
        "Ragonvalia",
        "Salazar",
        "San Calixto",
        "San Cayetano",
        "Santiago",
        "Sardinata",
        "Silos",
        "Teorama",
        "Tibú",
        "Toledo",
        "Villa Caro",
        "Villa del Rosario",
    ),
	'PUT' => array(
        "Colón",
        "Leguízamo",
        "Mocoa",
        "Orito",
        "Puerto Asis",
        "Puerto Caicedo",
        "Puerto Guzmán",
        "San Francisco",
        "San Miguel",
        "Santiago",
        "Sibundoy",
        "Valle Del Guamuez",
        "Villagarzón",
    ),
	'QUI' => array(
        "Armenia",
        "Buenavista",
        "Calarca",
        "Circasia",
        "Córdoba",
        "Filandia",
        "Genova",
        "La Tebaida",
        "Montenegro",
        "Pijao",
        "Quimbaya",
        "Salento",
    ),
	'RIS' => array(
        "Apía",
        "Balboa",
        "Belén de Umbría",
        "Dosquebradas",
        "Guática",
        "La Celia",
        "La Virginia",
        "Marsella",
        "Mistrató",
        "Pereira",
        "Pueblo Rico",
        "Quinchía",
        "Santa Rosa de Cabal",
        "Santuario",
    ),
	'SAP' => array(
        "Providencia",
        "San Andrés",
    ),
	'SAN'  => array(   
        "Aguada",
        "Albania",
        "Aratoca",
        "Barbosa",
        "Barichara",
        "Barrancabermeja",
        "Betulia",
        "Bolívar",
        "Bucaramanga",
        "Cabrera",
        "California",
        "Capitanejo",
        "Carcasí",
        "Cepitá",
        "Cerrito",
        "Charalá",
        "Charta",
        "Chima",
        "Chipatá",
        "Cimitarra",
        "Concepción",
        "Confines",
        "Contratacion",
        "Coromoro",
        "Curití",
        "El Carmen de Chucurí",
        "El Guacamayo",
        "El Peñón",
        "El Playón",
        "Encino",
        "Enciso",
        "Florián",
        "Floridablanca",
        "Galán",
        "Gambita",
        "Girón",
        "Guaca",
        "Guadalupe",
        "Guapotá",
        "Guavatá",
        "Güepsa",
        "Hato",
        "Jesus María",
        "Jordán",
        "La Belleza",
        "La Paz",
        "Landázuri",
        "Lebrija",
        "Los Santos",
        "Macaravita",
        "Málaga",
        "Matanza",
        "Mogotes",
        "Molagavita",
        "Ocamonte",
        "Oiba",
        "Onzaga",
        "Palmar",
        "Palmas Del Socorro",
        "Páramo",
        "Piedecuesta",
        "Pinchote",
        "Puente Nacional",
        "Puerto Parra",
        "Puerto Wilches",
        "Rionegro",
        "Sabana de Torres",
        "San Andrés",
        "San Benito",
        "San Gil",
        "San Joaquín",
        "San José de Miranda",
        "San Miguel",
        "San Vicente De Chucurí",
        "Santa Bárbara",
        "Santa Helena del Opón",
        "Simacota",
        "Socorro",
        "Suaita",
        "Sucre",
        "Suratá",
        "Tona",
        "Valle de San José",
        "Vélez",
        "Vetas",
        "Villanueva",
        "Zapatoca",
    ),
	'SUC' => array(
        "Buenavista",
        "Caimito",
        "Chalán",
        "Coloso",
        "Corozal",
        "Coveñas",
        "El Roble",
        "Galeras",
        "Guaranda",
        "La Unión",
        "Los Palmitos",
        "Majagual",
        "Morroa",
        "Ovejas",
        "Palmito",
        "Sampués",
        "San Benito Abad",
        "San Juan De Betulia",
        "San Marcos",
        "San Onofre",
        "San Pedro",
        "Santiago De Tolú",
        "Sincé",
        "Sincelejo",
        "Sucre",
        "Tolú viejo",
    ),
	'TOL' => array(
        "Alpujarra",
        "Alvarado",
        "Ambalema",
        "Anzoátegui",
        "Armero",
        "Ataco",
        "Cajamarca",
        "Carmen de Apicalá",
        "Casabianca",
        "Chaparral",
        "Coello",
        "Coyaima",
        "Cunday",
        "Dolores",
        "Espinal",
        "Falan",
        "Flandes",
        "Fresno",
        "Guamo",
        "Herveo",
        "Honda",
        "Ibagué",
        "Icononzo",
        "Lérida",
        "Líbano",
        "Mariquita",
        "Melgar",
        "Murillo",
        "Natagaima",
        "Ortega",
        "Palocabildo",
        "Piedras",
        "Planadas",
        "Prado",
        "Purificación",
        "Rioblanco",
        "Roncesvalles",
        "Rovira",
        "Saldaña",
        "San Antonio",
        "San Luis",
        "Santa Isabel",
        "Suárez",
        "Valle de San Juan",
        "Venadillo",
        "Villahermosa",
        "Villarica",
    ),
	'VAC' => array(
        "Alcalá",
        "Andalucía",
        "Ansermanuevo",
        "Argelia",
        "Bolívar",
        "Buenaventura",
        "Bugalagrande",
        "Caicedonia",
        "Cali",
        "Calima",
        "Candelaria",
        "Cartago",
        "Dagua",
        "El Águila",
        "El Cairo",
        "El Cerrito",
        "El Dovio",
        "Florida",
        "Ginebra",
        "Guacarí",
        "Guadalajara De Buga",
        "Jamundí",
        "La Cumbre",
        "La Union",
        "La Victoria",
        "Obando",
        "Palmira",
        "Pradera",
        "Restrepo",
        "Riofrío",
        "Roldanillo",
        "San Pedro",
        "Sevilla",
        "Toro",
        "Trujillo",
        "Tuluá",
        "Ulloa",
        "Versalles",
        "Vijes",
        "Yotoco",
        "Yumbo",
        "Zarzal",
    ),
	'VAU' => array(
        "Carurú",
        "Mitú",
        "Pacoa",
        "Papanaua",
        "Taraira",
        "Yavaraté",
	    ),
	'VIC' => array(
        "Cumaribo",
        "La Primavera",
        "Puerto Carreño",
        "Santa Rosalia",
    )
);
